name: e2e-tests

on: [pull_request]
    
jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Clang (libc++15)
      run: |
        sudo apt update
        sudo apt install -y clang-15
        
    - uses: bazel-contrib/setup-bazel@0.8.1
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Store build cache per workflow.
        disk-cache: ${{ github.workflow }}
        # Share repository cache between workflows.
        repository-cache: true
        bazelrc: |
          common --enable_bzlmod
          build --color=yes
          build --action_env CC=/usr/bin/clang-15
          build --action_env CXX=/usr/bin/clang++-15

        
    - name: Verify query parameters
      run: |
        bazel test //test:verify_query_params --test_output=streamed

    - name: Verify headers
      run: |
        bazel test //test:verify_headers --test_output=streamed

    - name: Process fixed body
      run: |
        bazel test //test:process_fixed_body --test_output=streamed

    - name: Drain fixed body
      run: |
        bazel test //test:drain_fixed_body --test_output=streamed
        
    - name: Process chunked body
      run: |
        bazel test //test:process_chunked_body --test_output=streamed

    - name: Drain chunked body
      run: |
        bazel test //test:drain_chunked_body --test_output=streamed
