name: e2e-tests

on: [pull_request]
    
jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup GCC 11
      run: |
        sudo apt update
        sudo apt install -y g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
        sudo update-alternatives --config gcc
        sudo update-alternatives --config g++
        gcc --version
        g++ --version
        
    - uses: bazel-contrib/setup-bazel@0.8.1
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Store build cache per workflow.
        disk-cache: ${{ github.workflow }}
        # Share repository cache between workflows.
        repository-cache: true
        
    - name: Verify query parameters
      run: |
        bazel test //test:verify_query_params --test_output=streamed

    - name: Verify headers
      run: |
        bazel test //test:verify_headers --test_output=streamed

    - name: Process fixed body
      run: |
        bazel test //test:process_fixed_body --test_output=streamed

    - name: Drain fixed body
      run: |
        bazel test //test:drain_fixed_body --test_output=streamed
        
    - name: Process chunked body
      run: |
        bazel test //test:process_chunked_body --test_output=streamed

    - name: Drain chunked body
      run: |
        bazel test //test:drain_chunked_body --test_output=streamed
