name: e2e-tests

on: [pull_request]
    
jobs:
  e2e_tests:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
        
    - uses: bazel-contrib/setup-bazel@0.8.1
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Store build cache per workflow.
        disk-cache: ${{ github.workflow }}
        # Share repository cache between workflows.
        repository-cache: true
        bazelrc: |
          build --color=yes

        
    - name: Verify query parameters
      working-directory: ./test
      run: |
        bazel test //:verify_query_params --test_output=streamed

    - name: Verify headers
      working-directory: ./test
      run: |
        bazel test //:verify_headers --test_output=streamed

    - name: Process fixed body
      working-directory: ./test
      run: |
        bazel test //:process_fixed_body --test_output=streamed

    - name: Drain fixed body
      working-directory: ./test
      run: |
        bazel test //:drain_fixed_body --test_output=streamed
        
    - name: Process chunked body
      working-directory: ./test
      run: |
        bazel test //:process_chunked_body --test_output=streamed

    - name: Drain chunked body
      working-directory: ./test
      run: |
        bazel test //:drain_chunked_body --test_output=streamed
